#%RAML 1.0
title: PoomPackComposer
version: v1
description: Flexio PoomPackComposer API
baseUri: https://api.flexio.io/poom-pack-composer
mediaType: application/json

/packages:
  displayName: Repository
  post:
    headers:
      X-version: string
      X-artifact-id: string
      X-vendor: string
    body: file
    responses:
      201:
  /packages.json:
    displayName: Packages
    get:
      responses:
        200:
         body: JsonPackage

types:
  JsonPackage:
    type: object
    properties:
      packages: object

  Package:
    type: object
    properties:
      name: string
      version: string
      dist: Dist

  Dist:
    type: object
    properties:
      type: string
      url: string